# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0002_auto_20170310_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNGImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('png_file', models.ImageField(upload_to='slices/')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AlterModelOptions(
            name='imageseries',
            options={'verbose_name_plural': 'Image Series'},
        ),
        migrations.AddField(
            model_name='imageseries',
            name='images',
            field=models.ManyToManyField(to='slicer.PNGImage'),
        ),
    ]
